# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokl < Formula
  desc "Local development environment orchestrator"
  homepage "https://github.com/shahin-bayat/lokl"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.1.2/lokl_0.1.2_darwin_amd64.tar.gz"
      sha256 "5d440333206e1e7d62bb3234872d7750cac947e30af93a6ba93bc454d73e2246"

      def install
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.1.2/lokl_0.1.2_darwin_arm64.tar.gz"
      sha256 "685b2efea960ada24487cb258f2e93092f70bc9052b4182e6f54d7b6a4045630"

      def install
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.1.2/lokl_0.1.2_linux_amd64.tar.gz"
      sha256 "37a9a1857f4b768f5342dd997338a009993af269bf497b5e3c30e6237ee17876"
      def install
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.1.2/lokl_0.1.2_linux_arm64.tar.gz"
      sha256 "d51b0b230435b9b26fb8bfca0c3e8e8d723a02003010f3fd3e915839024cb466"
      def install
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end
end
