# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokl < Formula
  desc "Local development environment orchestrator"
  homepage "https://github.com/shahin-bayat/lokl"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.4.0/lokl_0.4.0_darwin_amd64.tar.gz"
      sha256 "a26f748e186f02bf3b9cd6fc894475b2eba8fe6656c7b51da7c092404a51969a"

      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.4.0/lokl_0.4.0_darwin_arm64.tar.gz"
      sha256 "adcc8348263c63786765f597adf85466754be3e5dbedfe47dc6073157e5dee03"

      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.4.0/lokl_0.4.0_linux_amd64.tar.gz"
      sha256 "5069b15f17a2a0c2f7031918038fd9bd91b903b46ca13a5da1faa42f0a265f9d"
      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.4.0/lokl_0.4.0_linux_arm64.tar.gz"
      sha256 "c182c78c1794c099edbf0009cc80a86d44b29289f340b9cb487e0fb07c31a446"
      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end
end
