# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokl < Formula
  desc "Local development environment orchestrator"
  homepage "https://github.com/shahin-bayat/lokl"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.6.1/lokl_0.6.1_darwin_amd64.tar.gz"
      sha256 "c8dbc92fe716c1204d67b2c55b6f9dc5d64ff0e81095ce4c52764155855c21a2"

      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.6.1/lokl_0.6.1_darwin_arm64.tar.gz"
      sha256 "d53b4194cfb4e8071f50070023d2a2449030135023ff06bfee90d87b2a89f3f3"

      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.6.1/lokl_0.6.1_linux_amd64.tar.gz"
      sha256 "fd57e1386019f0641f6351970bdfd85d7c8e395f017e3e312fbfd1ae79bae609"
      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahin-bayat/lokl/releases/download/v0.6.1/lokl_0.6.1_linux_arm64.tar.gz"
      sha256 "9e0ff06c53cc80e254a2d9b4762fe19bd555f5d4e3935b5a1407445a888833c6"
      define_method(:install) do
        bin.install "lokl"
        generate_completions_from_executable(bin/"lokl", "completion")
      end
    end
  end
end
